name: firedns
description: A DNS over HTTPS client
display_name: Fire DNS
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7


flutter:
  uses-material-design: true

